In [1]:
import numpy as np
import pandas as pd

In [2]:
#1d 
data=pd.DataFrame(((1,1),(2,2),(3,3),(4,4),(5,5)),columns=('x','y'))
x_average=data.mean(axis=0).iloc[0]
fenzi=((data.loc[:,'x']-x_average)*data.loc[:,'y']).sum()
fenmu=(data.loc[:,'x']**2).sum()-(data.loc[:,'x'].sum()**2)/len(data)
w=fenzi/fenmu
b=(data['y']-w*data['x']).sum()/len(data)


def f(x):
    return x*w+b
f(6)

np.float64(6.0)

In [3]:
data=pd.DataFrame(((1,3,1),(2,4,2.5),(3,6,3),(4,5,5),(5,3,5)),columns=('x1','x2','y'))

In [4]:
data

   x1  x2    y
0   1   3  1.0
1   2   4  2.5
2   3   6  3.0
3   4   5  5.0
4   5   3  5.0

In [5]:
data2=data.reindex(columns=['x1','x2','z','y'])
data2['z']=1
data2

   x1  x2  z    y
0   1   3  1  1.0
1   2   4  1  2.5
2   3   6  1  3.0
3   4   5  1  5.0
4   5   3  1  5.0

In [6]:
#privious

#it's trouble and mess to deal with DataFrame and Series
X=data2.loc[:,'x1':'z']
#X=data2.loc[:,'x1':'z'].values
#y=data['y'].values

w=np.linalg.inv((X.T)@X)@(X.T)@data['y']
#w=np.linalg.inv((X.T)@X)@(X.T)@y

j=pd.DataFrame([[6,2,1],[7,3,1]])
#j=np.array([[6,2,1],[7,3,1],[8,7,1]])
print(j.T,'\n\n',pd.DataFrame(w).T)

pd.DataFrame(w).T@j.T
#w.T@j

   0  1
0  6  7
1  2  3
2  1  1

           0         1         2
0  1.040299  0.097015 -0.228358

          0         1
0  6.207463  7.344776

In [7]:
#now   use numpy array


X=data2.loc[:,'x1':'z'].values
y=data['y'].values

w=np.linalg.inv((X.T)@X)@(X.T)@y
j=np.array([[6,2,1],[7,3,1]])#.reshape(2,3)
print(j.T,'\n\n',w.T)

w.T@j.T

[[6 7]
 [2 3]
 [1 1]]

 [ 1.04029851  0.09701493 -0.22835821]

array([6.20746269, 7.34477612])

In [37]:
#Sigmoid
sigmoid_data=pd.DataFrame([(0,0,0),(1,1,1)],columns=['key1','key2','y'])
sigmoid_data

   key1  key2  y
0     0     0  0
1     1     1  1

In [38]:
sigmoid_data['b']=1
X=sigmoid_data[['b','key1','key2']].values
Y=sigmoid_data['y'].values

#w0=np.array(X.mean(axis=0))

w0=np.array([0.5,0.5,0.5])
print(X,'\n\n',Y,'\n\n',w0)

[[1 0 0]
 [1 1 1]]

 [0 1]

 [0.5 0.5 0.5]

In [39]:
print(w0@X.T)
p_1=pow(np.e,w0@X.T)/(1+pow(np.e,w0@X.T))#posibility of +
                                        #p_2=1/(1+pow(np.e,w0@X.T))
print(p_1)
loss=-np.mean(Y*np.log(p_1)+(1-Y)*np.log(1-p_1))  #改了一下，加上了mean
print(loss)

#loss为交叉熵损失,sum(y_true*log(y_pred))

[0.5 1.5]
[0.62245933 0.81757448]
0.5877451310814296

In [40]:
alpha=0.01
n=2

for i in range(10000):
    w0=w0+1/n*alpha*X.T@(Y-p_1).T
    p_1=pow(np.e,w0@X.T)/(1+pow(np.e,w0@X.T))
    
    if i % 1000 == 0:
        loss = -np.mean(Y * np.log(p_1 + 1e-8) + (1-Y) * np.log(1-p_1 + 1e-8)) #添加小常数防止除以0; np.mean()
        print(f"迭代 {i}, 损失: {loss:.6f}")
print(w0)

#we can use 'While' loop to get loss<=0.05.
#But keep in mind that you'd better set a deadline in case of limitless loop!!

迭代 0, 损失: 0.587095
迭代 1000, 损失: 0.253951
迭代 2000, 损失: 0.150870
迭代 3000, 损失: 0.104934
迭代 4000, 损失: 0.079728
迭代 5000, 损失: 0.064009
迭代 6000, 损失: 0.053341
迭代 7000, 损失: 0.045655
迭代 8000, 损失: 0.039868
迭代 9000, 损失: 0.035361
[-3.13456142  3.49565037  3.49565037]

In [13]:
test=np.array([[0.1,0],[0.8,0.3],[0.6,0.4]])
print(test,test.shape)
ones=np.ones([test.shape[0],1])#if set only test.shape[0],the array 'ones' is 1d
print(ones)
test=np.concatenate([ones,test],axis=1)
print(test,test.shape)

[[0.1 0. ]
 [0.8 0.3]
 [0.6 0.4]] (3, 2)
[[1.]
 [1.]
 [1.]]
[[1.  0.1 0. ]
 [1.  0.8 0.3]
 [1.  0.6 0.4]] (3, 3)

In [14]:
#!result=[]#though we can use array.append(),but it return a new array and it's not effective. So it's better to ues list there.
#!np.random.seed(17)
#!for i in range(test.shape[0]):
#!    pro=1/(1+pow(np.e,-w0@test[i].T)
#!    if pro>0.5:    ###！不能直接和0.5比较，必须把结果也变成概率
#!        print(pro)
#!        print('\n---a try---\n',test,'\n\n',w0,'\n\n',test@w0.T,'\n------\n')    #test.T@W?  ###stupid
#!        result.append(1)
#!    elif pro<0.5:
#!        print(pro)
#!        result.append(0)
#!    else:
#!        result.append(int(np.random.randint(0,2,size=1)[0]))
#!***********
#![out]:
#!-2.7784190791742205
#!0.7100254148546151

#!---a try---
#! [[1.  0.1 0. ]
#! [1.  0.8 0.3]
#! [1.  0.6 0.4]] 

#! [-3.12726353  3.48844449  3.48844449] 

#! [-2.77841908  0.71002541  0.36118097] 
#!------

#!0.36118096545173156
#!***********

#!#print(test,'\n\n',np.array(result).reshape(len(result),1))
#!result_array=np.concatenate([test,np.array(result).reshape(len(result),1)],axis=1)
result=1/(1+np.e**(-test@w0))
result=(result>0.5).astype(int)    #not so good
result_array=np.concatenate([test,result.T.reshape(len(result),1)],axis=1)
result_frame=pd.DataFrame(result_array[:,1:],columns=['key1','key2','prediction'])
result_frame

   key1  key2  prediction
0   0.1   0.0         0.0
1   0.8   0.3         1.0
2   0.6   0.4         1.0

In [15]:
#multi-classification

In [16]:
multi_data=pd.DataFrame([[0,0,0],[1,1,1],[0,1,2],[0.9,0.8,1]],columns=['x1','x2','y'])
multi_data

    x1   x2  y
0  0.0  0.0  0
1  1.0  1.0  1
2  0.0  1.0  2
3  0.9  0.8  1

In [17]:
#set One and Rest
###means notes to learn
#choose_pn=multi_data.set_index('y',append=True)

def set_positive(data,positive_class):
    positive=data.loc[(slice(None),positive_class),:]
    y_positive=np.ones(len(positive))
###positive=choose_pn.xs(0,level=1)    #way1
    
###print(positive.loc[(slice(None),1),:])    #right,way2
#      x1   x2
#  y          
#1 1  1.0  1.0
#3 1  0.9  0.8

###print(positive.loc[(slice(None),1)])    #Wrong. Because 1 is seen as columns

###see this
###print(positive.loc[(slice(None),'x1')])
#  y
#0  0    0.0
#1  1    1.0
#2  2    0.0
#3  1    0.9

    #print(choose_pn,'\n\n',positive,'\n\n',y_positive)

    nagetive=data.drop(index=positive.index)
    y_nagetive=np.zeros(len(nagetive))
    #print('\n------\n',nagetive,'\n\n',y_nagetive)


    X=np.concatenate([positive,nagetive])    #we can use 'concatenate' for DataFrames and theyran will become a array
    b=np.ones((len(X),1))
    X=np.concatenate([b,X],axis=1)
    Y=np.concatenate([y_positive,y_nagetive])
    #print('\n\n******\n',X,'\n\n',Y)

    return (X,Y)
    #this maybe a little inconvenient?

##y must be 1d

In [18]:
choose_pn=multi_data.set_index('y',append=True)
X,Y=set_positive(choose_pn,0)

In [19]:
X

array([[1. , 0. , 0. ],
       [1. , 1. , 1. ],
       [1. , 0. , 1. ],
       [1. , 0.9, 0.8]])

In [20]:
Y

array([1., 0., 0., 0.])

In [21]:
def get_w(X,Y,w,alpha=0.01,count=10000):
    p_1=1/(1+np.exp(-w@X.T))#posibility of +   #防止数值太大溢出
#p_2=1/(1+pow(np.e,w0@X.T))
#print(p_1)
    loss=-(Y*np.log(p_1)+(1-Y)*np.log(1-p_1))
#print(loss)
#loss为交叉熵损失,sum(y_true*log(y_pred))


    for i in range(count):
        
        s=X.T@(Y-p_1).T
        w=w+1/n*alpha*s

        #print(X.T,'\n',p_1,'\n',(Y-p_1).T,'\n',X.T@(Y-p_1).T)        
        #w0=w0+1/n*alpha*X.T@(Y-p_1).T
        p_1=1/(1+np.exp(-w@X.T))
    
#        if i % 1000 == 0:
#            loss = -np.mean(Y * np.log(p_1 + 1e-8) + (1-Y) * np.log(1-p_1 + 1e-8)) #添加小常数防止除以0; np.mean()
#            print(f"迭代 {i}, 损失: {loss:.6f}")
    loss = -np.mean(Y * np.log(p_1 + 1e-8) + (1-Y) * np.log(1-p_1 + 1e-8))
    print(f'lose:{loss}')
    return w

In [22]:
w_primary=np.array([0.5,0.5,0.5])
w=get_w(X,Y,w_primary)

lose:0.027131502177638128

In [23]:
w

array([ 2.68913599, -2.58898913, -6.17159389])

In [24]:
def get_result(w,test,test_columns):
    test_columns.append('prediction_result')
    
    ones=np.ones([test.shape[0],1])
    test=np.concatenate([ones,test],axis=1)
    #print(test,w)
    
    result=1/(1+np.exp(-test@w))
    result_class=(result>0.5).astype(int)    #not so good 1.=? 2.we need to select the max
    result_array=np.concatenate([test,result_class.T.reshape(len(result),1)],axis=1)
    result_frame=pd.DataFrame(result_array[:,1:],columns=test_columns)
    return (result,result_frame)

In [25]:
#test=np.array([[0.1,0],[0.8,0.3],[0.6,0.4]])
#get_result(w,test,['x1','x2'])

In [26]:
#formal_prediction

In [27]:
test=np.array([[0.1,0],[0.8,0.3],[0.6,0.4]])

In [28]:
w_primary=np.array([0.5,0.5,0.5])
final_result=pd.Series(-1,index=[-1])
final_result.name=-1
for i in range(3):
    X,Y=set_positive(choose_pn,i)
    w=get_w(X,Y,w_primary)
    result_probability,result=get_result(w,test,['x1','x2'])
    final_result=pd.concat([final_result,pd.Series(result_probability,name=f'class_{i}')],axis=1)
    print(f'when {i} is pasitive:\n{result}\n')
final_result=final_result.drop(index=[-1],columns=[-1])  #index=[]

print(final_result,'\n')
print(dict(final_result.idxmax(axis=1)))

lose:0.027131502177638128
when 0 is pasitive:
    x1   x2  prediction_result
0  0.1  0.0                1.0
1  0.8  0.3                0.0
2  0.6  0.4                0.0

lose:0.029439536530444045
when 1 is pasitive:
    x1   x2  prediction_result
0  0.1  0.0                0.0
1  0.8  0.3                1.0
2  0.6  0.4                1.0

lose:0.04719397262045785
when 2 is pasitive:
    x1   x2  prediction_result
0  0.1  0.0                0.0
1  0.8  0.3                0.0
2  0.6  0.4                0.0

    class_0   class_1   class_2
0  0.919104  0.055573  0.033445
1  0.225564  0.919943  0.002328
2  0.208681  0.733314  0.013033

{0: 'class_0', 1: 'class_1', 2: 'class_1'}

In [440]:

#wait ovo